import { Team, Holding, Transaction, LeaderboardEntry, MatchPending, AuditLogItem } from './types';

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'france',
    name: 'France',
    code: 'FRA',
    flagUrl: 'https://flagcdn.com/w80/fr.png',
    tier: 1,
    price: 1200,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [1200, 1200],
    fixtures: []
  },
  {
    id: 'spain',
    name: 'Spain',
    code: 'SPA',
    flagUrl: 'https://flagcdn.com/w80/es.png',
    tier: 1,
    price: 1200,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [1200, 1200],
    fixtures: []
  },
  {
    id: 'england',
    name: 'England',
    code: 'ENG',
    flagUrl: 'https://flagcdn.com/w80/gb-eng.png',
    tier: 1,
    price: 1200,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [1200, 1200],
    fixtures: []
  },
  {
    id: 'portugal',
    name: 'Portugal',
    code: 'POR',
    flagUrl: 'https://flagcdn.com/w80/pt.png',
    tier: 1,
    price: 1200,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [1200, 1200],
    fixtures: []
  },
  {
    id: 'germany',
    name: 'Germany',
    code: 'GER',
    flagUrl: 'https://flagcdn.com/w80/de.png',
    tier: 1,
    price: 1200,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [1200, 1200],
    fixtures: []
  },
  {
    id: 'brazil',
    name: 'Brazil',
    code: 'BRA',
    flagUrl: 'https://flagcdn.com/w80/br.png',
    tier: 1,
    price: 1200,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [1200, 1200],
    fixtures: []
  },
  {
    id: 'argentina',
    name: 'Argentina',
    code: 'ARG',
    flagUrl: 'https://flagcdn.com/w80/ar.png',
    tier: 1,
    price: 1200,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [1200, 1200],
    fixtures: []
  },
  {
    id: 'netherlands',
    name: 'Netherlands',
    code: 'NED',
    flagUrl: 'https://flagcdn.com/w80/nl.png',
    tier: 1,
    price: 1200,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [1200, 1200],
    fixtures: []
  },
  {
    id: 'norway',
    name: 'Norway',
    code: 'NOR',
    flagUrl: 'https://flagcdn.com/w80/no.png',
    tier: 2,
    price: 900,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [900, 900],
    fixtures: []
  },
  {
    id: 'trkiye',
    name: 'Türkiye',
    code: 'TUR',
    flagUrl: 'https://flagcdn.com/w80/tr.png',
    tier: 2,
    price: 900,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [900, 900],
    fixtures: []
  },
  {
    id: 'senegal',
    name: 'Senegal',
    code: 'SEN',
    flagUrl: 'https://flagcdn.com/w80/sn.png',
    tier: 2,
    price: 900,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [900, 900],
    fixtures: []
  },
  {
    id: 'belgium',
    name: 'Belgium',
    code: 'BEL',
    flagUrl: 'https://flagcdn.com/w80/be.png',
    tier: 2,
    price: 900,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [900, 900],
    fixtures: []
  },
  {
    id: 'uruguay',
    name: 'Uruguay',
    code: 'URU',
    flagUrl: 'https://flagcdn.com/w80/uy.png',
    tier: 2,
    price: 900,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [900, 900],
    fixtures: []
  },
  {
    id: 'morocco',
    name: 'Morocco',
    code: 'MAR',
    flagUrl: 'https://flagcdn.com/w80/ma.png',
    tier: 2,
    price: 900,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [900, 900],
    fixtures: []
  },
  {
    id: 'ecuador',
    name: 'Ecuador',
    code: 'ECU',
    flagUrl: 'https://flagcdn.com/w80/ec.png',
    tier: 2,
    price: 900,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [900, 900],
    fixtures: []
  },
  {
    id: 'croatia',
    name: 'Croatia',
    code: 'CRO',
    flagUrl: 'https://flagcdn.com/w80/hr.png',
    tier: 2,
    price: 900,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [900, 900],
    fixtures: []
  },
  {
    id: 'ivorycoast',
    name: 'Ivory Coast',
    code: 'IVC',
    flagUrl: 'https://flagcdn.com/w80/ci.png',
    tier: 2,
    price: 900,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [900, 900],
    fixtures: []
  },
  {
    id: 'colombia',
    name: 'Colombia',
    code: 'COL',
    flagUrl: 'https://flagcdn.com/w80/co.png',
    tier: 2,
    price: 900,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [900, 900],
    fixtures: []
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    code: 'SUI',
    flagUrl: 'https://flagcdn.com/w80/ch.png',
    tier: 2,
    price: 900,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [900, 900],
    fixtures: []
  },
  {
    id: 'sweden',
    name: 'Sweden',
    code: 'SWE',
    flagUrl: 'https://flagcdn.com/w80/se.png',
    tier: 2,
    price: 900,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [900, 900],
    fixtures: []
  },
  {
    id: 'japan',
    name: 'Japan',
    code: 'JPN',
    flagUrl: 'https://flagcdn.com/w80/jp.png',
    tier: 3,
    price: 600,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [600, 600],
    fixtures: []
  },
  {
    id: 'unitedstates',
    name: 'United States',
    code: 'USA',
    flagUrl: 'https://flagcdn.com/w80/us.png',
    tier: 3,
    price: 600,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [600, 600],
    fixtures: []
  },
  {
    id: 'austria',
    name: 'Austria',
    code: 'AUT',
    flagUrl: 'https://flagcdn.com/w80/at.png',
    tier: 3,
    price: 600,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [600, 600],
    fixtures: []
  },
  {
    id: 'mexico',
    name: 'Mexico',
    code: 'MEX',
    flagUrl: 'https://flagcdn.com/w80/mx.png',
    tier: 3,
    price: 600,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [600, 600],
    fixtures: []
  },
  {
    id: 'canada',
    name: 'Canada',
    code: 'CAN',
    flagUrl: 'https://flagcdn.com/w80/ca.png',
    tier: 3,
    price: 600,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [600, 600],
    fixtures: []
  },
  {
    id: 'algeria',
    name: 'Algeria',
    code: 'ALG',
    flagUrl: 'https://flagcdn.com/w80/dz.png',
    tier: 3,
    price: 600,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [600, 600],
    fixtures: []
  },
  {
    id: 'paraguay',
    name: 'Paraguay',
    code: 'PAR',
    flagUrl: 'https://flagcdn.com/w80/py.png',
    tier: 3,
    price: 600,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [600, 600],
    fixtures: []
  },
  {
    id: 'scotland',
    name: 'Scotland',
    code: 'SCO',
    flagUrl: 'https://flagcdn.com/w80/gb-sct.png',
    tier: 3,
    price: 600,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [600, 600],
    fixtures: []
  },
  {
    id: 'czechia',
    name: 'Czechia',
    code: 'CZE',
    flagUrl: 'https://flagcdn.com/w80/cz.png',
    tier: 3,
    price: 600,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [600, 600],
    fixtures: []
  },
  {
    id: 'southkorea',
    name: 'South Korea',
    code: 'KOR',
    flagUrl: 'https://flagcdn.com/w80/kr.png',
    tier: 3,
    price: 600,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [600, 600],
    fixtures: []
  },
  {
    id: 'egypt',
    name: 'Egypt',
    code: 'EGY',
    flagUrl: 'https://flagcdn.com/w80/eg.png',
    tier: 3,
    price: 600,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [600, 600],
    fixtures: []
  },
  {
    id: 'australia',
    name: 'Australia',
    code: 'AUS',
    flagUrl: 'https://flagcdn.com/w80/au.png',
    tier: 3,
    price: 600,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [600, 600],
    fixtures: []
  },
  {
    id: 'drcongo',
    name: 'DR Congo',
    code: 'DRC',
    flagUrl: 'https://flagcdn.com/w80/cd.png',
    tier: 3,
    price: 600,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [600, 600],
    fixtures: []
  },
  {
    id: 'uzbekistan',
    name: 'Uzbekistan',
    code: 'UZB',
    flagUrl: 'https://flagcdn.com/w80/uz.png',
    tier: 3,
    price: 600,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [600, 600],
    fixtures: []
  },
  {
    id: 'iran',
    name: 'Iran',
    code: 'IRN',
    flagUrl: 'https://flagcdn.com/w80/ir.png',
    tier: 3,
    price: 600,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [600, 600],
    fixtures: []
  },
  {
    id: 'ghana',
    name: 'Ghana',
    code: 'GHA',
    flagUrl: 'https://flagcdn.com/w80/gh.png',
    tier: 4,
    price: 400,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [400, 400],
    fixtures: []
  },
  {
    id: 'bosniaherzegovina',
    name: 'Bosnia & Herzegovina',
    code: 'BIH',
    flagUrl: 'https://flagcdn.com/w80/ba.png',
    tier: 4,
    price: 400,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [400, 400],
    fixtures: []
  },
  {
    id: 'panama',
    name: 'Panama',
    code: 'PAN',
    flagUrl: 'https://flagcdn.com/w80/pa.png',
    tier: 4,
    price: 400,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [400, 400],
    fixtures: []
  },
  {
    id: 'tunisia',
    name: 'Tunisia',
    code: 'TUN',
    flagUrl: 'https://flagcdn.com/w80/tn.png',
    tier: 4,
    price: 400,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [400, 400],
    fixtures: []
  },
  {
    id: 'jordan',
    name: 'Jordan',
    code: 'JOR',
    flagUrl: 'https://flagcdn.com/w80/jo.png',
    tier: 4,
    price: 400,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [400, 400],
    fixtures: []
  },
  {
    id: 'newzealand',
    name: 'New Zealand',
    code: 'NZL',
    flagUrl: 'https://flagcdn.com/w80/nz.png',
    tier: 4,
    price: 400,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [400, 400],
    fixtures: []
  },
  {
    id: 'iraq',
    name: 'Iraq',
    code: 'IRQ',
    flagUrl: 'https://flagcdn.com/w80/iq.png',
    tier: 4,
    price: 400,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [400, 400],
    fixtures: []
  },
  {
    id: 'capeverde',
    name: 'Cape Verde',
    code: 'CPV',
    flagUrl: 'https://flagcdn.com/w80/cv.png',
    tier: 4,
    price: 400,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [400, 400],
    fixtures: []
  },
  {
    id: 'saudiarabia',
    name: 'Saudi Arabia',
    code: 'KSA',
    flagUrl: 'https://flagcdn.com/w80/sa.png',
    tier: 4,
    price: 400,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [400, 400],
    fixtures: []
  },
  {
    id: 'haiti',
    name: 'Haiti',
    code: 'HAI',
    flagUrl: 'https://flagcdn.com/w80/ht.png',
    tier: 4,
    price: 400,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [400, 400],
    fixtures: []
  },
  {
    id: 'southafrica',
    name: 'South Africa',
    code: 'RSA',
    flagUrl: 'https://flagcdn.com/w80/za.png',
    tier: 4,
    price: 400,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [400, 400],
    fixtures: []
  },
  {
    id: 'curaao',
    name: 'Curaçao',
    code: 'CUW',
    flagUrl: 'https://flagcdn.com/w80/cw.png',
    tier: 4,
    price: 400,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [400, 400],
    fixtures: []
  },
  {
    id: 'qatar',
    name: 'Qatar',
    code: 'QAT',
    flagUrl: 'https://flagcdn.com/w80/qa.png',
    tier: 4,
    price: 400,
    priceChange24h: 0,
    group: 'Group A',
    matchday: 'Matchday 1',
    isLocked: false,
    stats: { goalsScored: 0, goalsConceded: 0, cleanSheets: 0, winDrawLoss: '0-0-0' },
    history: [400, 400],
    fixtures: []
  }
];

export const INITIAL_HOLDINGS: Holding[] = [
  { teamId: 'argentina', shares: 15, avgPrice: 130.00 },
  { teamId: 'netherlands', shares: 30, avgPrice: 85.20 },
  { teamId: 'france', shares: 10, avgPrice: 150.00 },
  { teamId: 'japan', shares: 100, avgPrice: 12.20 },
  { teamId: 'brazil', shares: 10, avgPrice: 410.00 }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx1',
    type: 'BUY',
    teamId: 'japan',
    shares: 300,
    price: 12.20,
    timestamp: 'Today, 14:30 UTC'
  },
  {
    id: 'tx2',
    type: 'SELL',
    teamId: 'england',
    shares: 100,
    price: 38.50,
    timestamp: 'Yesterday, 09:15 UTC'
  },
  {
    id: 'tx3',
    type: 'BUY',
    teamId: 'france',
    shares: 150,
    price: 42.50,
    timestamp: 'Oct 12, 11:00 UTC'
  }
];

export const LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    traderName: 'QuantKing',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=100',
    value: 16500,
    returnPct: 65.0,
    holdings: 14
  },
  {
    rank: 2,
    traderName: 'DataShark',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=100',
    value: 14200,
    returnPct: 42.0,
    holdings: 9
  },
  {
    rank: 3,
    traderName: 'Pellle_Fan',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=100',
    value: 13800,
    returnPct: 38.0,
    holdings: 7
  },
  {
    rank: 4,
    traderName: 'ViniVidiVici',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=100',
    value: 13500,
    returnPct: 35.0,
    holdings: 12
  },
  {
    rank: 5,
    traderName: 'MessiMagic',
    avatarUrl: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?auto=format&fit=crop&q=80&w=100',
    value: 13100,
    returnPct: 31.0,
    holdings: 5
  },
  {
    rank: 42,
    traderName: 'Tactical Speculator',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=100',
    value: 12450,
    returnPct: 24.5,
    holdings: 8,
    isCurrentUser: true
  }
];

export const INITIAL_MATCHES_PENDING: MatchPending[] = [
  {
    id: 'm1',
    teamAId: 'spain',
    teamBId: 'germany',
    goalsA: 2,
    goalsB: 1,
    stage: 'FINAL',
    isCompleted: false,
    stats: ['ESP (2)', 'GER (1)']
  },
  {
    id: 'm2',
    teamAId: 'japan',
    teamBId: 'korea',
    goalsA: 0,
    goalsB: 0,
    stage: 'FINAL (AET)',
    isCompleted: false,
    stats: ['Clean Sheet', 'JPN Penalties']
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'log1',
    source: 'SYSTEM AUTO',
    timestamp: '10:42 AM',
    message: 'Settled ARG vs MEX. Prices updated successfully.',
    borderColor: 'border-world-cup-green'
  },
  {
    id: 'log2',
    source: 'ADMIN (ROOT)',
    timestamp: '09:15 AM',
    message: 'Manual Bankruptcy triggered for MEX.',
    borderColor: 'border-error'
  },
  {
    id: 'log3',
    source: 'ADMIN (ROOT)',
    timestamp: 'Yesterday',
    message: 'Force override settlement on ENG vs USA (Correction applied).',
    borderColor: 'border-secondary-fixed-dim'
  },
  {
    id: 'log4',
    source: 'SYSTEM AUTO',
    timestamp: 'Yesterday',
    message: 'Settled FRA vs AUS. Prices updated successfully.',
    borderColor: 'border-world-cup-green'
  }
];
